//Debriefing
var debrief_text = '<strong>Study Debriefing</strong><br>'
	debrief_text += '<p class="debrief"><strong>Background:</strong> The patterns you rated are called <em>fractals</em>. The term fractal describes a class of irregular curves or shapes for which any suitably chosen part is similar in shape to a given larger or smaller part when magnified or reduced to the same size. Fractal properties are found throughout the natural and manmade world. The series of animations you saw today displayed animated fractal patterns of a varying complexity.</p>'
	debrief_text += '<p class="debrief"><strong>Purpose of this study:</strong> We hope to better understand how the perception of static fractals differs from the perception of animated fractals, and how the speed of the animated patterns influences people&apos;s perception of them. Fractals allow us to study the perception of aesthetic properties (e.g. the perceived level of beauty in an image) without using recognizable content, which makes them an excellent tool for studying abstract aesthetic judgement.</p>'
	debrief_text += '<p class="debrief"><strong>Your part:</strong> Your participation has helped us to further understand how humans perceive these patterns across different levels of speed and complexity. This research with allow us to better understand how the visual system and brain process our ever-changing visual environments.'
	debrief_text += '<p class="debrief"><strong>Feedback and Further information:</strong> If you have additional questions about this study, please feel free to ask the researcher, Nathan Gonzales-Hess at nhess @ uoregon.edu. If you have any questions concerning your rights as a research participant, please contact Research Compliance Services, 5237 University of Oregon, Eugene, OR 97403, 541-346-2510, or email researchCompliance @ uoregon.edu. You can also email the Human Subjects Coordinator for psychology and linguistics research at hscoord @ uoregon.edu. '

//Dynamic Prompts
var	complex_text = '<div class="intro">You are going to see a series of animations.<br><br></div>'
	complex_text += '<div class="intro">Move the slider to indicate how <strong style="text-transform:capitalize">COMPLEX</strong> you find each animation.<br><br></div>'
	complex_text +=	'<div class="intro">0 = Least Complex<br></div>'
	complex_text += '<div class="intro">1 = Most Complex<br><br></div>'
	complex_text += '<div class="intro">Remember to use the <strong><em>entire range</em></strong> of the slider to make your ratings.<br></div>'
	complex_text += '<div class="intro">Please <strong><em>take your time</em></strong> and carefully consider each rating you make.<br><br></div>'	
	complex_text += '<div class="intro">The study has five parts, and should take about 45 minutes to complete.<br><br></div>'

var interest_text = '<div class="intro">You are about to view a new series of animations.<br><br></div>'
	interest_text += '<div class="intro">You will evaluate them based on a different descriptor.<br><br></div>'
	interest_text += '<div class="intro">Move the slider to indicate how <strong style="text-transform:capitalize">INTERESTING</strong> you find each animation.<br><br></div>'
	interest_text += '<div class="intro">0 = Least Interesting<br></div>'
	interest_text += '<div class="intro">1 = Most Interesting<br><br></div>'
	interest_text += '<div class="intro">Remember to use the <strong><em>entire range</em></strong> of the slider to make your ratings.<br></div>'
	interest_text += '<div class="intro">Please <strong><em>take your time</em></strong> and carefully consider each rating you make.<br><br></div>'	

var relaxing_text = '<div class="intro">You are about to view a new series of animations.<br><br></div>'
	relaxing_text += '<div class="intro">You will evaluate them based on a different descriptor.<br><br></div>'
	relaxing_text += '<div class="intro">Move the slider to indicate how <strong style="text-transform:capitalize">RELAXING</strong> you find each animation.<br><br></div>'
	relaxing_text += '<div class="intro">0 = Least Relaxing<br></div>'
	relaxing_text += '<div class="intro">1 = Most Relaxing<br><br></div>'
	relaxing_text += '<div class="intro">Remember to use the <strong><em>entire range</em></strong> of the slider to make your ratings.<br></div>'
	relaxing_text += '<div class="intro">Please <strong><em>take your time</em></strong> and carefully consider each rating you make.<br><br></div>'	

var natural_text = '<div class="intro">You are about to view a new series of animations.<br><br></div>'
	natural_text += '<div class="intro">You will evaluate them based on a different descriptor.<br><br></div>'
	natural_text += '<div class="intro">Move the slider to indicate how <strong style="text-transform:capitalize">NATURAL</strong> you find each animation.<br><br></div>'
	natural_text +=	'<div class="intro">0 = Least Natural<br></div>'
	natural_text += '<div class="intro">1 = Most Natural<br><br></div>'
	natural_text += '<div class="intro">Remember to use the <strong><em>entire range</em></strong> of the slider to make your ratings.<br></div>'
	natural_text += '<div class="intro">Please <strong><em>take your time</em></strong> and carefully consider each rating you make.<br><br></div>'	

var appealing_text = '<div class="intro">You are about to view a new series of animations.<br><br></div>'
	appealing_text += '<div class="intro">You will evaluate them based on a different descriptor.<br><br></div>'
	appealing_text += '<div class="intro">Move the slider to indicate how <strong style="text-transform:capitalize">APPEALING</strong> you find each animation.<br><br></div>'
	appealing_text += '<div class="intro">0 = Least Appealing<br></div>'
	appealing_text += '<div class="intro">1 = Most Appealing<br><br></div>'
	appealing_text += '<div class="intro">Remember to use the <strong><em>entire range</em></strong> of the slider to make your ratings.<br></div>'
	appealing_text += '<div class="intro">Please <strong><em>take your time</em></strong> and carefully consider each rating you make.<br><br></div>'	