//Debreifing
var debrief_text = '<strong>Study Debriefing</strong><br>'
	debrief_text += '<p class="debrief"><strong>Background:</strong> The patterns you rated are called <em>fractals</em>. The term fractal describes a class of irregular curves or shapes for which any suitably chosen part is similar in shape to a given larger or smaller part when magnified or reduced to the same size. Fractal properties are found throughout the natural and manmade world. The series of animations you saw today displayed animated fractal patterns of a varying complexity.</p>'
	debrief_text += '<p class="debrief"><strong>Purpose of this study:</strong> We hope to better understand how the perception of static fractals differs from the perception of animated fractals, and how the speed of the animated patterns influences people&apos;s perception of them. Fractals allow us to study the perception of aesthetic properties (e.g. the perceived level of beauty in an image) without using recognizable content, which makes them an excellent tool for studying abstract aesthetic judgement.</p>'
	debrief_text += '<p class="debrief"><strong>Your part:</strong> Your participation has helped us to further understand how humans perceive these patterns across different levels of speed and complexity. This research with allow us to better understand how the visual system and brain process our ever-changing visual environments.'
	debrief_text += '<p class="debrief"><strong>Feedback and Further information:</strong> If you have additional questions about this study, please feel free to ask the researcher, Nathan Gonzales-Hess at nhess @ uoregon.edu. If you have any questions concerning your rights as a research participant, please contact Research Compliance Services, 5237 University of Oregon, Eugene, OR 97403, 541-346-2510, or email researchCompliance @ uoregon.edu. You can also email the Human Subjects Coordinator for psychology and linguistics research at hscoord @ uoregon.edu. '

//Dynamic Prompts
var complex_text = '<style> div {display: none;} </style>'
	complex_text += '<div>You are going to see a series of animations.<br><br></div>'
	complex_text += '<div>Move the slider to indicate how <strong style="text-transform:capitalize">COMPLEX</strong> you find each animation.<br><br></div>'
	complex_text +=	'<div>0 = Least Complex<br></div>'
	complex_text += '<div>1 = Most Complex<br><br></div>'
	complex_text += '<div>Remember to use the <strong><em>entire range</em></strong> of the slider to make your ratings.<br></div>'
	complex_text += '<div>Please <strong><em>take your time</em><strong> and carefully consider each rating you make. <br><br></div>'	
	complex_text += '<div>The study will take approximately 1 hour to complete.<br></div>'
	complex_text += '<script> $( "div" ).first().show( "fast", function showNext() {$( this ).next( "div" ).show( "fast", showNext )}); </script>'

var interest_text = 'You are going to see a series of animations.<br><br>'
	interest_text += 'Move the slider to indicate how <strong style="text-transform:capitalize">Interesting</strong> you find each animation.<br><br>'
	interest_text += '0 = Least Interesting<br>'
	interest_text += '1 = Most Interesting<br><br>'
	interest_text += 'Remember to use the <strong><em>entire range</em></strong> of the slider to make your ratings.<br>'
	interest_text += 'Please <em>take your time</em> and carefully consider each rating you make. <br><br>'	

var relaxing_text = 'You are going to see a series of animations.<br><br>'
	relaxing_text += 'Move the slider to indicate how <strong style="text-transform:capitalize">Relaxing</strong> you find each animation.<br><br>'
	relaxing_text += '0 = Least Relaxing<br>'
	relaxing_text += '1 = Most Relaxing<br><br>'
	relaxing_text += 'Remember to use the <strong><em>entire range</em></strong> of the slider to make your ratings.<br>'
	relaxing_text += 'Please <em>take your time</em> and carefully consider each rating you make. <br><br>'	

var natural_text = 'You are going to see a series of animations.<br><br>'
	natural_text += 'Move the slider to indicate how <strong style="text-transform:capitalize">Natural</strong> you find each animation.<br><br>'
	natural_text +=	'0 = Least Natural<br>'
	natural_text += '1 = Most Natural<br><br>'
	natural_text += 'Remember to use the <strong><em>entire range</em></strong> of the slider to make your ratings.<br>'
	natural_text += 'Please <em>take your time</em> and carefully consider each rating you make. <br><br>'	

var appealing_text = 'You are going to see a series of animations.<br><br>'
	appealing_text += 'Move the slider to indicate how <strong style="text-transform:capitalize">Appealing</strong> you find each animation.<br><br>'
	appealing_text += '0 = Least Appealing<br>'
	appealing_text += '1 = Most Appealing<br><br>'
	appealing_text += 'Remember to use the <strong><em>entire range</em></strong> of the slider to make your ratings.<br>'
	appealing_text += 'Please <em>take your time</em> and carefully consider each rating you make. <br><br>'	

//Still Prompts
var complex_text_stl = 'You are going to see a series of images.<br><br>'
	complex_text_stl += 'Move the slider to indicate how <strong style="text-transform:capitalize">COMPLEX</strong> you find each image.<br><br>'
	complex_text_stl +=	'0 = Least Complex<br>'
	complex_text_stl += '1 = Most Complex<br><br>'
	complex_text_stl += 'Please use the <strong><em>entire range</em></strong> of the slider to make your ratings.<br><br>'

var interest_text_stl = 'You are going to see a series of images.<br><br>'
	interest_text_stl += 'Move the slider to indicate how <strong style="text-transform:capitalize">Interesting</strong> you find each image.<br><br>'
	interest_text_stl += '0 = Least Interesting<br>'
	interest_text_stl += '1 = Most Interesting<br><br>'
	interest_text_stl += 'Please use the <strong><em>entire range</em></strong> of the slider to make your ratings.<br><br>'

var relaxing_text_stl = 'You are going to see a series of images.<br><br>'
	relaxing_text_stl += 'Move the slider to indicate how <strong style="text-transform:capitalize">Relaxing</strong> you find each image.<br><br>'
	relaxing_text_stl += '0 = Least Relaxing<br>'
	relaxing_text_stl += '1 = Most Relaxing<br><br>'
	relaxing_text_stl += 'Please use the <strong><em>entire range</em></strong> of the slider to make your ratings.<br><br>'

var natural_text_stl = 'You are going to see a series of images.<br><br>'
	natural_text_stl += 'Move the slider to indicate how <strong style="text-transform:capitalize">Natural</strong> you find each image.<br><br>'
	natural_text_stl +=	'0 = Least Natural<br>'
	natural_text_stl += '1 = Most Natural<br><br>'
	natural_text_stl += 'Please use the <strong><em>entire range</em></strong> of the slider to make your ratings.<br><br>'

var appealing_text_stl = 'You are going to see a series of images.<br><br>'
	appealing_text_stl += 'Move the slider to indicate how <strong style="text-transform:capitalize">Appealing</strong> you find each image.<br><br>'
	appealing_text_stl += '0 = Least Appealing<br>'
	appealing_text_stl += '1 = Most Appealing<br><br>'
	appealing_text_stl += 'Please use the <strong><em>entire range</em></strong> of the slider to make your ratings.<br><br>'